server:
  port: 8080
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MotoraZenit?serverTimezone=UTC 
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1706
  
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      jdbc:
        lob:
          non_contextual_creation: true